language: python
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
sudo: false
script:
  - sh test.sh
  - sleep 30
  - '[[ "$TRAVIS_JOB_NUMBER" != *.4 ]] # fail job 4'
  - env
  - |
    python travis_wonderwall.py job=3 version=3.4 branch=master <<BASH
      echo do
      echo a
      echo bunch
      echo of
      echo stuff
      echo here
matrix:
  allow_failures:
    - python: 3.5
