language: python
python:
  - 2.7
  - 3.3
  - 3.4
sudo: false
script:
  - sh test.sh
after_success:
  - |
    python travis_wonderwall.py job=2 version=3.4 branch=master <<BASH
      echo do
      echo a
      echo bunch
      echo of
      echo stuff
      echo here
