language: node_js
node_js:
  - 4.2
  - node
sudo: false
script:
  - echo "Doing something..."
  - env
  - sleep 3
  - echo "Done"
after_success:
  - |
    python travis_wonderwall.py || (
      echo do
      echo a
      echo bunch
      echo of
      echo stuff
      echo here
    )
